# Generated by Django 3.2.3 on 2021-05-25 12:30


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Town', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('County', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Zip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('FileLoc', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Condition', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('SwapComp', models.BooleanField(default=False)),
                ('Archived', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=False)),
                ('SwapAgrd', models.BooleanField(default=False)),
                ('Category', models.ManyToManyField(related_name='Category', to='itemmgmt.Categories')),
                ('Feedback', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usermgmt.feedback')),
                ('PhotoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.photos')),
            ],
        ),
    ]
