# Generated by Django 3.2.3 on 2021-05-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=200)),
                ('ItemCat', models.CharField(max_length=200)),
                ('ItemCond', models.CharField(max_length=200)),
                ('ItemLoc', models.CharField(max_length=200)),
                ('SwapComp', models.BooleanField(default=False)),
                ('ItemArch', models.BooleanField(default=False)),
                ('ItemAct', models.BooleanField(default=False)),
                ('SwapAgrd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('PhotoID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('FileLoc', models.URLField()),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='PhotoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.photos'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=200)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.items')),
            ],
        ),
    ]
