# Generated by Django 3.2.3 on 2021-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Archived',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Feedback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='PhotoID',
            new_name='photo_id',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='SwapAgrd',
            new_name='swap_agrd',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='SwapComp',
            new_name='swap_comp',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='County',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Town',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Zip',
            new_name='zip',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='FileLoc',
            new_name='file_loc',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='items',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='items',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='ID',
        ),
        migrations.AddField(
            model_name='categories',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(related_name='category', to='itemmgmt.Categories'),
        ),
        migrations.AddField(
            model_name='items',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
