# Generated by Django 3.2.3 on 2021-06-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0002_auto_20210527_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='photo_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.photos'),
        ),
    ]
