# Generated by Django 3.2.3 on 2021-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0005_rename_zip_address_zipcode'),
        ('itemmgmt', '0003_alter_items_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='feedback',
        ),
        migrations.AddField(
            model_name='items',
            name='feedback',
            field=models.ManyToManyField(related_name='ItemFeedback', to='usermgmt.Feedback'),
        ),
    ]
