# Generated by Django 3.2.3 on 2021-06-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0004_auto_20210601_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='items',
            name='photo_id',
            field=models.ManyToManyField(default=None, to='itemmgmt.Photos'),
        ),
    ]
