# Generated by Django 3.2.3 on 2021-06-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0005_auto_20210601_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ManyToManyField(to='itemmgmt.Categories'),
        ),
    ]
