# Generated by Django 3.2.3 on 2021-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0006_alter_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
