# Generated by Django 3.2.3 on 2021-06-03 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0009_alter_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='upload',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
