# Generated by Django 3.2.3 on 2021-06-03 12:40

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0010_auto_20210603_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
