# Generated by Django 3.2.3 on 2021-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0012_auto_20210603_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='file_loc',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
