# Generated by Django 3.2.3 on 2021-06-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0013_photos_file_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='file_loc',
        ),
        migrations.AddField(
            model_name='photos',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.items'),
        ),
    ]
