# Generated by Django 3.2.3 on 2021-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0005_rename_zip_address_zipcode'),
        ('itemmgmt', '0014_auto_20210603_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='image',
        ),
        migrations.AddField(
            model_name='items',
            name='photo_id',
            field=models.ManyToManyField(default=None, to='itemmgmt.Photos'),
        ),
        migrations.AddField(
            model_name='photos',
            name='upload',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='feedback',
            field=models.ManyToManyField(related_name='ItemFeedback', to='usermgmt.Feedback'),
        ),
    ]
