# Generated by Django 3.2.3 on 2021-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0015_auto_20210603_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
