# Generated by Django 3.2.3 on 2021-06-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0016_alter_photos_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='photo_id',
        ),
    ]
