# Generated by Django 3.2.3 on 2021-06-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0018_alter_items_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='feedback',
        ),
    ]
