# Generated by Django 3.2.3 on 2021-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0019_remove_items_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='item',
        ),
        migrations.AddField(
            model_name='items',
            name='photoID',
            field=models.ManyToManyField(default='None', to='itemmgmt.Photos'),
        ),
    ]
