# Generated by Django 3.2.3 on 2021-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0020_auto_20210603_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='item',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
