# Generated by Django 3.2.3 on 2021-06-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0021_photos_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemid', to='itemmgmt.items'),
        ),
    ]
