# Generated by Django 3.2.3 on 2021-06-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0022_alter_photos_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='item',
        ),
        migrations.AddField(
            model_name='photos',
            name='item',
            field=models.ManyToManyField(related_name='itemid', to='itemmgmt.Items'),
        ),
    ]
