# Generated by Django 3.2.3 on 2021-06-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0023_auto_20210604_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='item',
            field=models.ManyToManyField(default=None, related_name='itemid', to='itemmgmt.Items'),
        ),
    ]
