# Generated by Django 3.2.3 on 2021-06-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0024_alter_photos_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='item',
        ),
    ]
