# Generated by Django 3.2.3 on 2021-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0025_remove_photos_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='photoID',
        ),
        migrations.AddField(
            model_name='items',
            name='upload',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
