# Generated by Django 3.2.3 on 2021-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0026_auto_20210604_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='upload',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
