# Generated by Django 3.2.3 on 2021-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0027_alter_items_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='items',
            name='upload',
        ),
        migrations.AddField(
            model_name='items',
            name='upload',
            field=models.ManyToManyField(default=None, to='itemmgmt.Photos'),
        ),
    ]
