# Generated by Django 3.2.3 on 2021-06-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0029_auto_20210604_0756'),
        ('swaplist', '0004_auto_20210604_0756'),
        ('usermgmt', '0007_alter_feedback_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='itemmgmt.Categories'),
        ),
    ]
