# Generated by Django 3.2.3 on 2021-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0030_auto_20210604_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='upload',
            new_name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(default=None, upload_to='', verbose_name='uploads/'),
            preserve_default=False,
        ),
    ]
