# Generated by Django 3.2.3 on 2021-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0031_auto_20210604_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(default=None, upload_to='', verbose_name='uploads/'),
        ),
    ]
