# Generated by Django 3.2.3 on 2021-06-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0032_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.FileField(default=None, upload_to='', verbose_name='uploads/'),
        ),
    ]
