# Generated by Django 3.2.3 on 2021-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0033_auto_20210604_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
