# Generated by Django 3.2.3 on 2021-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0038_auto_20210605_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to='uploads/items'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.FileField(upload_to='uploads/items/images/'),
        ),
    ]
