# Generated by Django 3.2.3 on 2021-06-08 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0044_alter_item_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
