# Generated by Django 3.2.3 on 2021-06-08 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("usermgmt", "0014_profile_items"),
        ("itemmgmt", "0045_auto_20210608_0845"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usermgmt.appuser",
            ),
            preserve_default=False,
        ),
    ]
