# Generated by Django 3.2.4 on 2021-06-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=models.FileField(null=True, upload_to='profile_images'),
        ),
    ]
