# Generated by Django 3.2.4 on 2021-06-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0002_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
