# Generated by Django 3.2.3 on 2021-06-09 15:27

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0002_rename_user_cart_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(default='Tadley', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
