# Generated by Django 3.2.4 on 2021-06-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0002_alter_profile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
    ]
