# Generated by Django 3.2.4 on 2021-06-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0003_auto_20210617_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='profile_images/dummy-avatar.png', null=True, upload_to='profile_images'),
        ),
    ]
