# Generated by Django 3.2.4 on 2021-06-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("swapshop", "0005_auto_20210623_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="item",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="swapshop.wishlistitem",
            ),
            preserve_default=False,
        ),
    ]
