# Generated by Django 3.2.4 on 2021-06-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0006_wishlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
    ]
