# Generated by Django 3.2.4 on 2021-06-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0007_remove_wishlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='item',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='item',
            field=models.ManyToManyField(to='swapshop.Item'),
        ),
    ]
