# Generated by Django 3.2.4 on 2021-06-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("swapshop", "0008_auto_20210625_1447"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistitem",
            name="item",
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="item",
            field=models.ForeignKey(
                default=46060,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="swapshop.item",
            ),
            preserve_default=False,
        ),
    ]
