# Generated by Django 3.2.4 on 2021-06-25 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0009_auto_20210625_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swapshop.item'),
        ),
    ]
