# Generated by Django 3.2.4 on 2021-07-07 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swapshop', '0011_swaplist_swaplistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='ordered_by',
        ),
        migrations.AddField(
            model_name='swap',
            name='message_sent',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='swap',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('Like New', 'Like New'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Used', 'Used'), ('Poor', 'Poor'), ('Spares or Repair', 'Spares or Repair')], max_length=50),
        ),
    ]
