# Generated by Django 3.2.4 on 2021-07-07 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("swapshop", "0012_auto_20210707_1656"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swap",
            name="wish_list",
        ),
        migrations.AddField(
            model_name="swap",
            name="item",
            field=models.ForeignKey(
                default=46169,
                on_delete=django.db.models.deletion.CASCADE,
                to="swapshop.item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swap",
            name="swap_list",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="swapshop.swaplist",
            ),
            preserve_default=False,
        ),
    ]
