# Generated by Django 3.2.4 on 2021-07-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0013_auto_20210707_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='swap_list',
        ),
        migrations.AddField(
            model_name='swap',
            name='swap_list',
            field=models.ManyToManyField(to='swapshop.SwapList'),
        ),
    ]
