# Generated by Django 3.2.4 on 2021-07-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0015_auto_20210708_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='swap_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swapshop.swaplist'),
        ),
    ]
