# Generated by Django 3.2.4 on 2021-07-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0016_alter_swap_swap_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swap',
            old_name='email',
            new_name='email_from',
        ),
        migrations.AddField(
            model_name='swap',
            name='email_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
