# Generated by Django 3.2.4 on 2021-07-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0017_auto_20210708_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanted',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='wanted',
            name='location',
        ),
        migrations.RemoveField(
            model_name='wanted',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='ForSwap',
        ),
        migrations.DeleteModel(
            name='Wanted',
        ),
    ]
