# Generated by Django 3.2.4 on 2021-07-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0019_auto_20210709_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
    ]
