# Generated by Django 3.2.4 on 2021-07-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0020_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
