# Generated by Django 3.2.4 on 2021-07-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapshop', '0021_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='profile_images/dummy/dummy-avatar.png', null=True, upload_to='profile_images'),
        ),
    ]
