# Generated by Django 3.2.3 on 2021-05-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('HouseNum', models.IntegerField()),
                ('Street', models.CharField(max_length=200)),
                ('Town', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('County', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Zip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=200)),
                ('Comments', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('EmailVerified', models.BooleanField(default=False)),
                ('Phone', models.CharField(max_length=200)),
                ('Rating', models.IntegerField()),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.address')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Feedback', models.ManyToManyField(related_name='Feedback', to='usermgmt.Feedback')),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.profile')),
            ],
        ),
    ]
