# Generated by Django 3.2.3 on 2021-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='County',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='HouseNum',
            new_name='house_num',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Street',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Town',
            new_name='town',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='Zip',
            new_name='zip',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='EmailVerified',
            new_name='email_verified',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Feedback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ID',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
