# Generated by Django 3.2.3 on 2021-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_auto_20210527_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='feedback',
            field=models.ManyToManyField(related_name='Feedback', to='usermgmt.Feedback'),
        ),
    ]
