# Generated by Django 3.2.3 on 2021-05-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20210527_0940'),
        ('usermgmt', '0004_alter_profile_feedback'),
    ]

    operations = [
    ]
