# Generated by Django 3.2.3 on 2021-05-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_alter_profile_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
