# Generated by Django 3.2.3 on 2021-06-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0019_remove_items_feedback'),
        ('usermgmt', '0005_rename_zip_address_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.items'),
            preserve_default=False,
        ),
    ]
