# Generated by Django 3.2.3 on 2021-06-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmgmt', '0029_auto_20210604_0756'),
        ('usermgmt', '0006_feedback_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmgmt.item'),
        ),
    ]
