# Generated by Django 3.2.3 on 2021-06-08 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0008_admin_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermgmt.address'),
        ),
    ]
