# Generated by Django 3.2.3 on 2021-05-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemmgmt', '0001_initial'),
        ('usermgmt', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=200)),
                ('ConditionReq', models.CharField(max_length=200)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.items')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.users')),
            ],
        ),
        migrations.CreateModel(
            name='ForSwap',
            fields=[
                ('ID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('SwapAvail', models.BooleanField(default=False)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemID', to='itemmgmt.items')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmgmt.location')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.users')),
            ],
        ),
    ]
