# Generated by Django 3.2.3 on 2021-05-27 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swaplist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forswap',
            old_name='ItemID',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='forswap',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='forswap',
            old_name='SwapAvail',
            new_name='swap_avail',
        ),
        migrations.RenameField(
            model_name='wanted',
            old_name='ConditionReq',
            new_name='condition_req',
        ),
        migrations.RenameField(
            model_name='wanted',
            old_name='ItemID',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='wanted',
            old_name='Location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='forswap',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='forswap',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='wanted',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='wanted',
            name='UserID',
        ),
        migrations.AddField(
            model_name='forswap',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forswap',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanted',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanted',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
