# Generated by Django 3.2.3 on 2021-05-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaplist', '0002_auto_20210527_0925'),
        ('swaplist', '0002_auto_20210527_0940'),
    ]

    operations = [
    ]
